# Generated by Django 4.0.4 on 2022-12-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manytoone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporter',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
